# Source: mysql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: default
  labels:
    app.kubernetes.io/name: mysql
type: Opaque
data:
  mysql-root-password: "ek9ENjF1NDJJaw=="
  mysql-password: "N3R0WmxCUjlTeQ=="
