apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  application.properties: |
    spring.jpa.hibernate.ddl-auto=update
    spring.datasource.url=jdbc:mysql://mysql:3306/java_app_database
    spring.datasource.username=user1
    spring.datasource.password=password1
    server.port=9090
