apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: java-app
spec:
  replicas: {{ .Values.java.replicas }}
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: spring-app
        image: {{ .Values.java.image }}
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 20m
            memory: 256Mi
        env:
        # Define the environment variable
        - name: JAVA_OPTS
          value: "--spring.config.location=file:/config/application.properties"
        ports:
        - containerPort: {{ .Values.java.port }}
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: { .Release.Name }}i-configmap

