apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: java-app-deployment
  minReplicas: 1
  maxReplicas: {{ .Values.hpa.maxreplicas }}
  targetCPUUtilizationPercentage: 10
