apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - port: 8080
      targetPort: {{ .Values.service.targetport  }}
      name: web
