apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: java-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: java-app-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
