apiVersion: v1
appVersion: 0.0.1
description: A Helm chart for Pim
name: java-app
version: 0.0.11
sources:
- https://gitlab.plytix.com/plytixdevs/plytix-pim
maintainers:
- name: Javi
  email: javienet@gmail.com
